### ISSUE TITLE
BadgeOS Submenu Link

### ISSUE THREAD

**Issue by X-Raym** [opencredit/BadgeOS-Boilerplate-Add-on#2]
Hi ! 

Coue you please add a way to simply adding an admin page ounder the BadgeOS top level menu the sidebar ? 

I tried something like this 

```
public function add_admin_pages() { 
    // Set minimum role setting for menus 
    $minimum_role = badgeos_get_manager_capability(); 

    add_submenu_page( 
        'badgeos_badgeos', 
        __( 'BadgeOS Group Actions', 'badgeos-group-actions' ), 
        __( 'Group Actions', 'badgeos-group-actions' ), 
        $minimum_role, 
        'badgeos-group-actions', 
        array( $this, 'users_page' ) 
    ); 
} 
```

but for some reason it doesn t work well. My page is located in plugins/badgeos-group-actions-add-ons/badgeis-group-actions.php 

It redirects to http://127.0.0.1:4001/wordpress/wp-admin/admin.php?page=badgeos-group-actions with the famous not enough permission error.

The things is when I replace the menu domain by something more common such as tools.php it works flawlessly.
What did I missed ? 
Thanks !

**Comment by X-Raym** [comment]
Ok it seems that my hook call was simply too early, as explained on WordPress Codex.

```
add_action( 'admin_menu', array( $this, 'add_admin_pages' ), 999 );
```

**Comment by tw2113** [comment]
Woo, figured it out on your own :) :+1:

**Comment by X-Raym** [comment]
I tried during hours, but yes, finally :D
